# Generated by Django 4.2.7 on 2023-11-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jiomodel",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("mobile_number", models.BigIntegerField()),
                ("recharge_amount", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("succes", models.BooleanField()),
            ],
        ),
    ]
